GET http://localhost:4912

###

GET http://localhost:4912/todos?stop=true

###

GET http://localhost:4912/todos/2?stop=false

###

POST http://localhost:4912/todos
Content-Type: application/json

{
  "title": "First Todo",
  "description": "this is description",
  "category_id": 1,
  "progress": 20
}

###

PUT http://localhost:4912/todos/2
Content-Type: application/json

{
  "title": "First Todo Edit"
}

###

DELETE http://localhost:4912/todos/2