GET http://localhost:4912

###

GET http://localhost:4912/todos?stop=true

###

GET http://localhost:4912/todos/3?stop=false

###

POST http://localhost:4912/todos
Content-Type: application/json

{
  "title": "Third Todo",
  "description": "this is description",
  "category_id": 1,
  "progress": 20
}

###

PUT http://localhost:4912/todos/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG5fZG9lIiwiZW1haWwiOiJqb2huLmRvZUBleGFtcGxlLmNvbSIsImlhdCI6MTczODMwNTk5MCwiZXhwIjoxNzM4MzkyMzkwfQ.Jl9ebOSUUYUV5mFsOecyZHfUMEUHMWEfigTK-KeMB5M

{
  "title": "Second Todo Edit"
}

###

DELETE http://localhost:4912/todos/2

###

POST http://localhost:4912/auth/login
Content-Type: application/json

{
  "username": "john_doe",
  "password": "qwe123"
}