GET http://localhost:4912

###

GET http://localhost:4912/users?stop=true

###

GET http://localhost:4912/users/1?stop=false

###

POST http://localhost:4912/users
Content-Type: application/json

{
  "name": "Abdul"
}

###

PUT http://localhost:4912/users/1
Content-Type: application/json

{
  "name": "Esto"
}

###

DELETE http://localhost:4912/users/1